name: Browser Haram via Tailscale

on: 
  workflow_dispatch:

jobs:
  start-browser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # FIX DISINI: Ganti v2 jadi v3
      - name: Connect Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }} # (Opsional kalo mau ganti)
          # Kita tetep pake authkey aja biar lu ga ribet seting lagi
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: latest
          hostname: gh-action-browser
          # Tambahan biar ga rewel user-nya
          args: --advertise-exit-node

      - name: Deploy Chromium Webtop
        run: |
          echo "Gas tarik image..."
          docker run -d \
            --name=chrome-gacor \
            --security-opt seccomp=unconfined \
            -e PUID=1000 -e PGID=1000 \
            -e TZ=Asia/Jakarta \
            -p 3000:3000 \
            -p 3001:3001 \
            --shm-size="2gb" \
            lscr.io/linuxserver/chromium:latest
          
          echo "Tunggu bentar..."
          sleep 10

      - name: INFO CARA AKSES
        run: |
          TS_IP=$(tailscale ip -4)
          echo "========================================================"
          echo "ðŸ”¥ SUKSES JING! (Semoga) ðŸ”¥"
          echo "Link akses: http://$TS_IP:3000"
          echo "========================================================"

      - name: Keep Alive (Max 6 Jam)
        run: |
          echo "Sesi aktif... tekan Cancel Workflow kalo udah bosen."
          docker logs -f chrome-gacor
